aws/zarf.yaml
so they can be overlayed when doing a zarf deploy
=> AWS distro: Updating the rights on the loki folder 

.github/workflows/pipeline.aws.yaml, aws/loki/main.tf
[PR was merged](https://github.com/defenseunicorns/delivery-aws-iac/pull/194) so this needs to point back to `main` (since the `s3-force-delete-option` branch no longer exists) so that CI can work again.
=> Fix iac ref

.github/workflows/eks/config.yaml, .github/workflows/eks/zarf-config.yaml, defense-unicorns-distro/scripts/preflight.sh, values/neuvector.yaml
Bumping k8s version in advance of BB 2.0 per [this note](https://repo1.dso.mil/big-bang/bigbang/-/releases/2.0.0#user-content-release-notes-200:~:text=Please%20see%20our%20documentation%20page%20for%20more%20information%20on%20how%20to%20consume%20and%20deploy%20BigBang.%20This%20release%20was%20primarily%20tested%20on%20Kubernetes%201.26.3).
=> fix: bump refs to support k8s v1.26

values/istio.yaml
Allow services to access the public ingress gateway by default.
=> Enable hosts using the public ingress gateway to accessible

values/values.yaml
This is hard turned off instead of turning on when the kubernetes environment doesn't have it
=> enable metrics server again

aws/loki/main.tf
Currently the name of the S3 loki bucket is the cluster name followed by timestamp (ex. `rex-eks20230517215251115700000001`)
IaC overall creates numerous S3 buckets all of which contain the cluster name followed by a specific use description:
Ex.
```
rex-gr-sessionlogs-20230517153912748900000002
rex-sessionlogs-bastion-20230502153533507800000002
rex-accesslog-ee1820230502143103389600000001
```
I think it would be helpful for `aws-dubbd` creation of the loki S3 bucket to follow the same pattern.
=> add "loki" to the name of the s3 bucket

defense-unicorns-distro/scripts/teardown.sh, defense-unicorns-distro/zarf.yaml
Teardown commands will likely be reused for `onFailure` on an install, so pulling them out to a separate script file for better future reuse.
Also fixes a bug with the metrics-server deletion step, ensuring it is owned by BB before removing.
=> Pull teardown commands into script for reuse

aws/zarf-config.yaml, aws/zarf.yaml, cocowow/zarf-config.yaml, cocowow/zarf.yaml, defense-unicorns-distro/scripts/extract_flux.sh, defense-unicorns-distro/scripts/on_failure.sh, defense-unicorns-distro/scripts/reconcile_helmreleases.sh, defense-unicorns-distro/zarf-config.yaml, defense-unicorns-distro/zarf.yaml, k3d/zarf-config.yaml, k3d/zarf.yaml
The primary goal of this PR is to have Zarf catch failures of a DUBBD install/upgrade. This is accomplished by altering the `onDeploy.after` actions to add:
- wait on the `bigbang` gitrepository to have the correct BB version
- flux reconciliation of `bigbang` helmrelease (with source)
- kubectl patches to force reconciliation of all BB packages
Secondary addition was to add an `onFailure` action with additional debug (kubectl describe) *if* a helmrelease shows as being in a failed state. If no helmrelease shows as failed the debug log will still contain all helmrelease describes (baked into zarf extension).
=> Help Zarf catch upgrade failures

.gitignore
Failed Zarf commands leave behind directories, this PR adds them to the `.gitignore`
=> adds zarf directory artifacts to .gitignore

aws/values/aws-loki.yaml, defense-unicorns-distro/zarf.yaml, values/kiali.yaml, values/loki.yaml, values/promtail.yaml, values/values.yaml
Couple cleanup pieces:
- random comment
- random newline
- EFK + twistlock disable values (not needed post-2.0)
- logo/image link fix
Functional changes: Removed mTLS permissive override for kiali/promtail. This appears to work fine and has been set as the default in BB for a while now - I believe it was a legacy carryover that isn't necessary in current BB/DUBBD versions.
=> Cleanup values, mTLS STRICT for kiali/promtail

values/istio.yaml
Adds minimum TLS at the gateway in addition to the mesh config.
See https://repo1.dso.mil/big-bang/product/packages/istio-controlplane/-/issues/78#note_738607
Related to https://github.com/defenseunicorns/zarf-package-big-bang/issues/220
=> fix: set min tls version at gateway

README.md, aws/zarf-config.yaml, defense-unicorns-distro/scripts/cat_cert.sh, defense-unicorns-distro/scripts/cat_key.sh, defense-unicorns-distro/zarf-config.yaml, defense-unicorns-distro/zarf.yaml, k3d/zarf-config.yaml
Moving forward both the admin and tenant ingressGateways will use the same cert.
=> chore: update PUBLIC_{KEY,CERT}_FILE references to {KEY,CERT}_FILE 

aws/values/aws-istio.yaml, aws/zarf.yaml
Fixes missing annotations. Added only to dubbd-aws since these would not be applicable for k3d, etc.
=> fix: Add AWS LB annotations

values/istio.yaml
Switches istio "enterprise" mode on by default (Tetrate Istio Distribution). Everything came up healthy and all ingress worked fine in a quick test.
Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/221
=> Switch istio to TID by default

aws/loki/output.tf, aws/zarf.yaml
Attempt at resolving #244 
~~2 paths tested:~~
~~- When force_destroy is set to 'true' both S3 bucket and KMS key are deleted~~
~~- When force_destroy is set to 'false" only the S3 bucket is deleted~~
=> Delete both S3 and KMS when force_delete is set to true

.github/workflows/publish.dubbd.package.yaml, .github/workflows/tag-and-release.yaml
Adds a publish skeleton step to the DUBBD publishing workflow.
Also adds a job to publish core DUBBD.
With this addition every release would publish 6 packages: aws/k3d/"core" package+skeleton
BEGIN_COMMIT_OVERRIDE
chore: publish skeleton packages and DUBBD core package
END_COMMIT_OVERRIDE
=> chore: Publish skeleton and DUBBD core

README.md, aws/README.md, k3d/README.md
Adds upgrade documentation for DUBBD-AWS. Also fixes a few spots with the wrong package name.
Preview rendered: https://github.com/defenseunicorns/uds-package-dubbd/blob/aws-docs/aws/README.md
Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/14
=> DUBBD-AWS Upgrade Documentation

release-please-config.json
temporary change so all versions are patches (for now)
manual override option: still can force a version with a commit message:
```sh
git commit --allow-empty -m "chore: release 0.3.0" -m "Release-As: 0.3.0"
```
=> ci: config temp set releases to patch only

defense-unicorns-distro/zarf.yaml
Fixes the misplaced `files` block (indented incorrectly) which ensures that the on_failure script is pulled in properly.
=> fix: misplaced files in zarf.yaml

aws/README.md, aws/values/aws-istio.yaml, aws/zarf-config.yaml, aws/zarf.yaml
Changes:
- Adds a `private_tenant_lb` zarf var to configure whether the provisioned tenant elastic loadbalancer is public or private
- Adds actions before/after to cycle the tenant loadbalancer service if this value changes on an upgrade (ensures a new ELB is provisioned)
Notes:
- all logic was added to the AWS package as it is currently AWS specific but we could move to "core" DUBBD in the future if other flavors require the same variable/functionality
- bash scripting is not intended to be the final solution for "upgrade logic" - there are other proposed routes of doing things in a more programmatic approach w/testing, etc but as there is not a clear decision on that approach yet this was done with basic scripting
- this basic pattern would likely apply to all future upgrade logic as …
=> feat: allow configuring public/private tenant LB

.github/workflows/ci-on-pull-request-aws.yaml, .github/workflows/ci-on-pull-request-k3d.yaml
Relates to https://github.com/defenseunicorns/uds-package-dubbd/issues/216
Adds file paths in the workflows that are ignored, so that when there are changes to them, the workflows are not triggered
This creates a faster feedback loop by not running the pipelines for changes that do not impact the package or the pipelines themselves. For example, if I make a change to only the k3d package, only the k3d pipeline will run, and the AWS/EKS pipeline will be skipped because there are no changes to the AWS package or pipelines.
=> fix: Update workflow path filters

.github/workflows/ci-on-pull-request-dubbd-aws.yaml, .github/workflows/ci-on-pull-request-uds-core-aws.yaml
Standardizes around `paths-ignore` for all workflows to match k3d. Ensures that workflow changes + changes to "DUBBD vanilla" trigger a CI run since AWS imports from there.
=> chore: standardize workflow rules with paths-ignore

aws/dubbd-aws/zarf.yaml, aws/extract.sh
This change will use the downloaded Terraform binaries during a `zarf p deploy`.  Notice that this still uses the local Terraform install during `zarf p create`.
=> Use downloaded Terraform binary for a Zarf deploy.

k3d/.gitignore, k3d/local/manifests/metallb/metallb-native.yaml, k3d/local/scripts/k3d.sh
- Fix: metal-lb's speaker pod was failing due to not being able to access ConfigMaps
- Fix: Promtail pod wouldn't start because it couldn't access `/etc/machine-id`
- Removes extraneous args from the `k3d` command
- Adds artifacts to k3d .gitignore
- make sure we are dogfooding `k3d/local`?
=> fixes k3d local installation

.github/workflows/ci-on-pull-request-k3d.yaml, .github/workflows/ci-on-pull-request-rke2.yaml, .github/workflows/rke2/README.md, .github/workflows/rke2/main.tf, .github/workflows/rke2/storage-class.yaml, .github/workflows/rke2/variables.tf, .github/workflows/tag-and-release.yaml, .github/workflows/test-dubbd-rke2-install.yaml, rke2/README.md
Adds a CI test using upstream RKE2 on AWS terraform.
"AWS-specific" pieces (storage class mainly) would migrate away from AWS specific implementations over time as we develop rook/ceph, etc.
=> ci: add CI testing for RKE2

aws/route53-policy/main.tf
Ran into an issue where when I updated DUBBD-AWS, the update failed because the route53 policies already existed and the state stored in S3 wasn't being read
=> uncomments backend for route53policy

defense-unicorns-distro/zarf.yaml
This removes some dead variables from the DUBBD package.
=> chore: remove dead variables from DUBBD

.github/workflows/rke2/README.md, .github/workflows/rke2/main.tf, .github/workflows/rke2/variables.tf
Switches AMI for CI to the one from https://github.com/defenseunicorns/uds-rke2-image-builder
Also modifies TF to be a single server, 2 agent setup.
Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/502
=> chore: switch rke2 CI to uds-ami

aws/loki/main.tf, aws/loki/terraform.tfvars, aws/loki/variables.tf, aws/route53-policy/main.tf, aws/route53-policy/output.tf, aws/route53-policy/terraform.tfvars, aws/route53-policy/variables.tf, aws/velero/main.tf, aws/velero/terraform.tfvars, aws/velero/variables.tf
Previously, the Terraform modules would rely on the user's default AWS region.  This will use the region passed in from Zarf to determine the AWS region for Terraform operations.
I also applied some Terraform linting, so there are a lot of whitespace changes.  You may want to hide the whitespace changes for your review.
=> fix: Propagate region variable from Zarf to Terraform

values/kyverno.yaml
Override for this recent change:
https://repo1.dso.mil/big-bang/product/packages/kyverno/-/blob/main/chart/values.yaml?ref_type=heads#L377
Without this fix, policy exceptions outside of the `kyverno` namespace will not be incorporated & this output is seen on apply:
```sh
$ kubectl apply -f exception.yaml 
Warning: PolicyException resource namespace must match the defined namespace.
policyexception.kyverno.io/***** created
```
=> fix: remove kyverno exception ns boundary

defense-unicorns-distro/zarf.yaml
resolves #88 
add query to GITEA_RUNNING check that looks for deployment instead of statefulset. This is needed if someone uses a later version of the gitea helm chart (e.g. 9.5.1).
So far this works with deploying DUBBD on top of the maintained zarf init pkg as well as on top of custom init, and it fails if it finds neither.
=> feat: update DUBBD to handle custom zarf init package.

.github/test-infra/eks/config.yaml, .github/test-infra/eks/zarf.yaml
issue this addresses:
using latest ami (id: ami-0b1c494fc850ef41c / name: amazon-eks-node-1.27-v20240202) as of 02/06/2024 with eksctl, when running a zarf init (any version) the zarf registry pod fails to pull the injector image with an error.
error seen:
```console
pod/zarf-docker-registry-86d779b879-gmx52                   Failed to pull image "127.0.0.1:30636/library/registry:2.8.3": rpc error: code = Unknown desc = failed to pull and unpack image "127.0.0.1:30636/library/registry:2.8.3": failed to resolve reference "127.0.0.1:30636/library/registry:2.8.3": failed to do request: Head "https://127.0.0.1:30636/v2/library/registry/manifests/2.8.3": net/http: TLS handshake timeout
```
suspecting this may be an issue with the containerd version?
```
$ kubectl get no -owide
NAME …
```
=> ci: fix for eksctl to pin to a specific ami

README.md
update the README to provide notice of plans that DUBBD will be deprecated in favor of [uds-core](https://github.com/defenseunicorns/uds-core)
=> chore!: dubbd deprecation in summer of 2024, replaced by uds-core
