defenseunicorns/uds-package-dubbd

defense-unicorns-distro/cat_certs.sh
defense-unicorns-distro/cat_key.sh
defense-unicorns-distro/zarf-config.yaml
defense-unicorns-distro/zarf.yaml
renovate.json

PR to address refs to cert and key references and move the kyverno helmrelease delete before the webhook deletes.

fix: cert/key refs, move kyverno hr delete up, and update renovate

---

values/kyverno.yaml

Kyverno policies

---

values/authservice.yaml
values/neuvector.yaml
values/sso.yaml
values/values.yaml

A few values files need to be cleaned up.

Clean up a few values yaml files

---

.github/workflows/pipeline.aws.yaml
.github/workflows/pipeline.publish.yaml
aws/extract.sh
aws/loki/main.tf
aws/loki/terraform.tfvars
aws/zarf-config.yaml
aws/zarf.yaml

add linux versions for terraform

---

.github/workflows/pipeline.aws.yaml
.github/workflows/pipeline.dubbd.yaml
.github/workflows/pipeline.publish.yaml
.github/workflows/pipeline.yaml
renovate.json

addresses https://github.com/defenseunicorns/zarf-package-big-bang/issues/84

feat: update GH workflows for renovate automation

---

defense-unicorns-distro/zarf.yaml

This pr is to address [this issue](https://github.com/defenseunicorns/zarf-package-big-bang/issues/67)

Updating defense-unicorns-distro to only delete it's own gitrepos

---

.github/workflows/kms/main.tf

adding a terraform output for kms key alias to be used on the zarf-config.yaml

added kms alias tf output

---

defense-unicorns-distro/zarf.yaml

Small pre-flight check to create a zarf var `IS_UPGRADE` set to true/false based on BB HR existence. This var could be used in `onDeploy` actions and/or `onFailure` actions.
Potential funky edge case: the BB HR exists but isn't healthy yet

Add short pre-flight to detect if on an upgrade

---

aws/loki/main.tf

This is the first step in renaming these repos to follow the Terraform naming convention.

DRAFT: Update S3 and KMS UDS repo names to match the Terraform convention.

---

.github/workflows/pipeline.aws.yaml

Adds SHA env var to workflow step

adds env var to update step in workflow

---

.github/actions/latest-package-version/action.yaml
.github/workflows/pipeline.yaml
README.md
aws/zarf.yaml
k3d/zarf.yaml
renovate.json

Updates repo name to uds-package-dubbd

chore: updates repo name to uds-package-dubbd

---

.github/actions/latest-package-version/action.yaml
.github/workflows/test-aws-upgrade.yaml

Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/291

Update dubbd-aws package name in upgrade job

---

.github/workflows/DEPRECATED.pipeline.dubbd.yaml
.github/workflows/test-aws-package.yaml
.github/workflows/test-aws-upgrade.yaml

Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/302

fix: Update AWS config in CI to use OIDC auth

---

aws/zarf.yaml

Issue seen in CI where the zarf created shell for the actions does not like the `[[ <stuff> ]]` syntax + `==`.

fix: update conditionals on ingress upgrade to fix syntax

---

values/neuvector.yaml

to address https://github.com/defenseunicorns/uds-package-dubbd/issues/318

feat: enable auto_scan for neuvector by default

---

aws/README.md
aws/values/aws-istio.yaml
aws/zarf-config.yaml
aws/zarf.yaml

Identical to the changes in https://github.com/defenseunicorns/uds-package-dubbd/pull/299, just done for the admin ingress.
Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/315

fix: make admin ingress configurable

---

values/istio.yaml
values/kiali.yaml

Part 1 of https://github.com/defenseunicorns/uds-package-dubbd/issues/334
Changes:
- HPA for istiod with min 1 replica, max 3 replicas, 80% target CPU
- HPA for kiali with min 1 replica, max 3 replicas

feat: Adds HPA for istiod, modified HPA for kiali

---

.github/workflows/aws-nuke/aws-nuke-ci-config.yaml
.github/workflows/aws-nuke/aws-nuke-ci.yaml

This initial commit will run everyday at 1 AM Mountain and targets the following for deletion in the CI account.
- S3Object
- S3Bucket
- EC2Instance
- EKSNodegroups
- EKSCluster

Inital addition of aws-nuke workflows.

---

aws/loki/main.tf

- Adds data retention lifecycle policy to the Loki S3 bucket
- 30 days hot storage -> 365 days cold storage

adds data retention to Loki bucket

---

.github/workflows/test-dubbd-aws-install.yaml
.github/workflows/test-dubbd-aws-upgrade.yaml
.github/workflows/test-uds-core-aws-install.yaml
.github/workflows/test-uds-core-aws-upgrade.yaml
aws/README.md
aws/dubbd-aws/zarf-config.yaml
aws/dubbd-aws/zarf.yaml
aws/uds-core-aws/zarf-config.yaml
aws/uds-core-aws/zarf.yaml

Intentional decision to not just rename the variable:
- Allows for non-"true/false" things tied to ephemeral (we can "translate" the true/false ephemeral to any necessary "type")
- Allows for controlling the individual pieces on there own still if desired (maybe user wants to delete PVCs but keep Loki S3)
Closes https://github.com/defenseunicorns/uds-package-dubbd/issues/385

Tie force destroy to ephemeral var

---

defense-unicorns-distro/zarf.yaml

fix: fixes #390

---

aws/dubbd-aws/zarf.yaml
aws/uds-core-aws/zarf.yaml
defense-unicorns-distro/zarf.yaml
values/kyverno.yaml

to address https://github.com/defenseunicorns/uds-package-dubbd/issues/380

feat: add kyverno ns exclude

---

aws/dubbd-aws/zarf.yaml
aws/uds-core-aws/zarf.yaml
defense-unicorns-distro/zarf.yaml
k3d/zarf.yaml
values/kyverno.yaml

prereq for https://github.com/defenseunicorns/uds-package-dubbd/pull/401 & https://github.com/defenseunicorns/uds-package-dubbd/issues/379

feat: add dubbd pre-upgrade & update refs

---

values/loki.yaml

feat: add HPA for Loki

---

values/istio.yaml

fixes https://github.com/defenseunicorns/uds-package-dubbd/issues/423

feat: add authservice istio extensionProvider

---

values/istio.yaml

Fixes https://github.com/defenseunicorns/uds-package-dubbd/issues/452
/cc @kirankt

fix: avoid conflicts with BB authservice package

---

.github/workflows/oscal/config-dubbd-aws-oscal-component.yaml
.github/workflows/oscal/config-dubbd-oscal-component.yaml
.github/workflows/oscal/config-uds-core-aws-oscal-component.yaml
aws/dubbd-aws/oscal-component.yaml
aws/uds-core-aws/oscal-component.yaml
oscal-component.yaml

Upstream BB NeuVector now includes oscal file. Updating configs to grab and include nevucector.

fix: updating oscal configs to include neuvector

---

defense-unicorns-distro/zarf.yaml

Fixes https://github.com/defenseunicorns/uds-package-dubbd/issues/473

fix: delete grafana onRemove

---

docs/adrs/0003-disable-kiali-operator-for-dubbd.md

addresses https://github.com/defenseunicorns/uds-package-dubbd/issues/491

docs: add adr for disabling kiali operator

---

values/kiali.yaml

to address https://github.com/defenseunicorns/uds-package-dubbd/issues/505

fix: kiali operator memory bump to fix OOM kill

---

defense-unicorns-distro/scripts/preflight.sh
defense-unicorns-distro/zarf.yaml

addresses concerns for dubbd in https://github.com/defenseunicorns/uds-cli/issues/4

feat: add more preflight checks

---

defense-unicorns-distro/scripts/preflight.sh
defense-unicorns-distro/zarf.yaml

resolves https://github.com/defenseunicorns/uds-package-dubbd/issues/574

fix: update preflight to remove deprecated arg

---

.github/workflows/oscal/config-dubbd-aws-oscal-component.yaml

Update file path location to fix an issue with component-generator breaking change.
Will further fix solution by implementing tags.

fix!: local component-generator break fix

---

values/kyverno-policies.yaml

this change is meant to fix https://github.com/defenseunicorns/uds-package-dubbd/issues/602

fix: kyverno image registry policy exception

---

defense-unicorns-distro/scripts/extract_flux.sh

fix: ostype not recognized

---

README.md

Please discontinue use of DUBBD and instead use uds-core:
https://github.com/defenseunicorns/uds-core

chore!: dubbd deprecated, replaced by uds-core
